// Spanish for the owner dashboard. Keyed by the exact English text used in the UI,
// so components just call tx("English text") and fall back to English if missing.
export const adminEs: Record<string, string> = {
  // shell + tabs
  "Dashboard": "Panel",
  "View site ↗": "Ver sitio ↗",
  "Sign out": "Cerrar sesión",
  "Dashboard sections": "Secciones del panel",
  "Bookings": "Reservas",
  "Services": "Servicios",
  "Add-ons": "Complementos",
  "Team": "Equipo",
  "Portfolio": "Portafolio",
  "Reviews": "Reseñas",
  "FAQ": "Preguntas frecuentes",
  "Studio & site": "Salón y sitio",
  "Loading…": "Cargando…",

  // login + gates
  "Owner login": "Acceso del propietario",
  "Welcome back": "Bienvenido(a) de nuevo",
  "Email": "Correo electrónico",
  "Password": "Contraseña",
  "Sign in": "Iniciar sesión",
  "Signing in…": "Iniciando sesión…",
  "That email or password is incorrect.": "Ese correo o contraseña es incorrecto.",
  "Supabase isn’t configured. Add NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY to .env.local.": "Supabase no está configurado. Agrega NEXT_PUBLIC_SUPABASE_URL y NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY en .env.local.",
  "One-time database setup": "Configuración única de la base de datos",
  "Open your Supabase project → SQL Editor → New query, paste the contents of supabase/schema.sql from this project, and press Run. Then reload this page.": "Abre tu proyecto de Supabase → SQL Editor → New query, pega el contenido de supabase/schema.sql de este proyecto y presiona Run. Luego recarga esta página.",
  "Not authorized": "No autorizado",
  "Claim this website": "Reclamar este sitio",
  "This account isn’t the owner of this site. Sign out and use the owner login.": "Esta cuenta no es la propietaria de este sitio. Cierra sesión y usa el acceso del propietario.",
  "No owner has been set up yet. If you’re the salon owner, claim the dashboard now. This can only be done once.": "Aún no hay un propietario configurado. Si eres el dueño o la dueña del salón, reclama el panel ahora. Solo se puede hacer una vez.",
  "I’m the owner. Claim it": "Soy el propietario(a). Reclamar",

  // banners + notes
  "Your website is showing sample content.": "Tu sitio web está mostrando contenido de muestra.",
  "Load the starter services, portfolio, reviews and FAQ into your database so you can edit them here.": "Carga los servicios, portafolio, reseñas y preguntas de ejemplo en tu base de datos para poder editarlos aquí.",
  "Load starter content": "Cargar contenido de ejemplo",
  "Load the starter services, portfolio, reviews and FAQ into your database? You can edit or delete everything afterwards.": "¿Cargar los servicios, portafolio, reseñas y preguntas de ejemplo en tu base de datos? Después podrás editar o borrar todo.",
  "Starter content loaded. Edit anything from the tabs.": "Contenido de ejemplo cargado. Edita lo que quieras desde las pestañas.",
  "Turn on Spanish for your content": "Activa el español para tu contenido",
  "One-time step: open Supabase → SQL Editor → New query, paste this, press Run, then reload this page.": "Paso único: abre Supabase → SQL Editor → New query, pega esto, presiona Run y recarga esta página.",
  "Copy SQL": "Copiar SQL",
  "Copied ✓": "Copiado ✓",
  "Add Spanish to your starter content": "Agrega español a tu contenido de ejemplo",
  "Visitors can switch the site to Spanish. Add ready-made Spanish for the starter services, portfolio, reviews and FAQ now; you can edit any of it afterwards.": "Los visitantes pueden cambiar el sitio a español. Agrega ahora el español ya preparado para los servicios, portafolio, reseñas y preguntas de ejemplo; después puedes editar lo que quieras.",
  "Add Spanish translations": "Agregar traducciones al español",
  "Spanish added to the starter content. Review it in each section (look for the “Español” boxes).": "Español agregado al contenido de ejemplo. Revísalo en cada sección (busca las cajas “Español”).",

  // section titles + blurbs
  "What clients can book. Price is the “from” price; duration controls how much calendar time it takes.": "Lo que los clientes pueden reservar. El precio es el precio “desde”; la duración define cuánto tiempo ocupa en el calendario.",
  "Optional extras clients can tack onto a service.": "Extras opcionales que los clientes pueden añadir a un servicio.",
  "People shown in “Meet the team” under the homepage banner. If this is empty, the owner card is shown automatically.": "Personas que aparecen en “Conoce al equipo” debajo del banner de inicio. Si está vacío, se muestra automáticamente la tarjeta del propietario.",
  "Upload your best work. Add a “before” photo to turn on the before/after slider.": "Sube tu mejor trabajo. Agrega una foto de “antes” para activar el deslizador antes/después.",
  "Client words on the Stories tab. Only add real reviews you have permission to share.": "Palabras de clientes en la pestaña Reseñas. Agrega solo reseñas reales que tengas permiso de compartir.",
  "Questions shown on the Studio tab.": "Preguntas que aparecen en la pestaña Salón.",

  // field labels + hints
  "Service name": "Nombre del servicio",
  "Category": "Categoría",
  "Description": "Descripción",
  "Starting price ($)": "Precio desde ($)",
  "Duration (minutes)": "Duración (minutos)",
  "Deposit ($)": "Depósito ($)",
  "0 = no deposit": "0 = sin depósito",
  "Name": "Nombre",
  "Short description": "Descripción corta",
  "Price ($)": "Precio ($)",
  "Adds (minutes)": "Suma (minutos)",
  "After photo (main image)": "Foto del después (imagen principal)",
  "Before photo (optional, enables the slider)": "Foto del antes (opcional, activa el deslizador)",
  "Title": "Título",
  "Linked service id": "ID del servicio vinculado",
  "The “Book this look” button preselects this service. Copy an id from the Services tab URL list, e.g. blonde-balayage.": "El botón “Reservar este look” preselecciona este servicio. Escribe el id del servicio, p. ej. blonde-balayage.",
  "Story": "Historia",
  "Time in chair (label)": "Tiempo en la silla (texto)",
  "e.g. 3.5 hrs": "p. ej. 3.5 h",
  "Placeholder art style": "Estilo del arte provisional",
  "Only used when no photo is uploaded.": "Solo se usa si no se sube una foto.",
  "Palette (placeholder art)": "Paleta (arte provisional)",
  "Photo": "Foto",
  "Role": "Cargo",
  "e.g. Color specialist": "p. ej. Especialista en color",
  "Short bio": "Biografía corta",
  "Instagram handle": "Usuario de Instagram",
  "without the @": "sin el @",
  "Client name": "Nombre del cliente",
  "Service they had": "Servicio que recibió",
  "Review": "Reseña",
  "Stars (1–5)": "Estrellas (1–5)",
  "Question": "Pregunta",
  "Answer": "Respuesta",
  // select options
  "Cut": "Corte",
  "Color": "Color",
  "Blonding": "Rubios",
  "Styling": "Peinado",
  "Texture": "Textura",
  "Bridal": "Novias",
  "straight": "liso",
  "wave": "ondulado",
  "curl": "rizado",
  "bob": "bob",

  // calendar
  "Calendar": "Calendario",
  "Every appointment at a glance. Click a day to see it, add a walk-in or phone booking, or block time off.": "Todas las citas de un vistazo. Haz clic en un día para verlo, agregar una cita sin reserva o por teléfono, o bloquear tiempo libre.",
  "Today": "Hoy",
  "Closed this day": "Cerrado este día",
  "No appointments this day.": "No hay citas este día.",
  "+ Add appointment": "+ Agregar cita",
  "Block time": "Bloquear tiempo",
  "Blocked": "Bloqueado",
  "Time off": "Tiempo libre",
  "Overlaps another appointment": "Se cruza con otra cita",
  "That time overlaps another appointment.": "Ese horario se cruza con otra cita.",
  "Appointment added.": "Cita agregada.",
  "Time blocked.": "Tiempo bloqueado.",
  "Service": "Servicio",
  "Time": "Hora",
  "Notes": "Notas",
  "No open times for that service on this day.": "No hay horarios libres para ese servicio este día.",
  "Save appointment": "Guardar cita",
  "Start": "Inicio",
  "Length": "Duración",
  "All day": "Todo el día",
  "Reason (optional)": "Motivo (opcional)",
  "Lunch, day off…": "Almuerzo, día libre…",
  "Block this time": "Bloquear este horario",
  "Extra protection against double-booking": "Protección extra contra doble reserva",
  "The site already hides times that would overlap. Run this once in Supabase → SQL Editor so the database itself refuses overlapping appointments too.": "El sitio ya oculta los horarios que se cruzarían. Ejecuta esto una vez en Supabase → SQL Editor para que la base de datos también rechace citas que se cruzan.",

  "Products": "Productos",
  "Product name": "Nombre del producto",
  "Online buy link (optional)": "Enlace para comprar en línea (opcional)",
  "If set, shows a “Buy online” button.": "Si lo pones, muestra un botón “Comprar en línea”.",
  "0 = don't show a price": "0 = no mostrar precio",
  "In stock": "Disponible",
  "Eyelash extensions": "Extensiones de pestañas",
  "Hair care": "Cuidado del cabello",
  "Shampoo & conditioner": "Champú y acondicionador",
  "Treatments": "Tratamientos",
  "Tools": "Herramientas",
  "Other": "Otros",
  "Shown on the Products page: eyelash extensions, shampoo, treatments and anything else you sell. Add a photo, price and description.": "Aparece en la página Productos: extensiones de pestañas, champú, tratamientos y todo lo que vendas. Agrega foto, precio y descripción.",

  "Stylist profile": "Perfil de la estilista",
  "Page text": "Textos de la página",
  "Salon & contact": "Salón y contacto",
  "The “Meet Fabiola” section on the homepage: her photo, name, headline, bio and the labels around it.": "La sección “Conoce a Fabiola” del inicio: su foto, nombre, título, biografía y las etiquetas alrededor.",
  "The hero headline, the ticker under it, the aftercare tips and the gift cards on the Studio tab.": "El título principal, la cinta de palabras debajo, los consejos de cuidado y las tarjetas de regalo de la pestaña Salón.",
  "Salon name, address, phone, hours and booking rules.": "Nombre del salón, dirección, teléfono, horario y reglas de reservas.",
  "Shown in the “Meet …” heading (first name) and the hero.": "Aparece en el título “Conoce a …” (primer nombre) y en la portada.",
  "Labels around it": "Etiquetas alrededor",
  "Small label above the heading": "Etiqueta pequeña sobre el título",
  "Blank = “Your stylist”.": "Vacío = “Tu estilista”.",
  "Word before the name": "Palabra antes del nombre",
  "Blank = “Meet”.": "Vacío = “Conoce a”.",
  "Button text": "Texto del botón",
  "Blank = “Book a consultation”.": "Vacío = “Reservar una consulta”.",
  "The three numbers": "Los tres números",
  "Hero headline": "Título principal",
  "Blank = built-in text.": "Vacío = texto predeterminado.",
  "Word 1": "Palabra 1",
  "Word 2 (colored)": "Palabra 2 (de color)",
  "Word 3": "Palabra 3",
  "Ticker under the hero": "Cinta de palabras bajo la portada",
  "Ticker words": "Palabras de la cinta",
  "Separate with commas. Blank = built-in list.": "Sepáralas con comas. Vacío = lista predeterminada.",
  "Aftercare tips": "Consejos de cuidado",
  "Shown at the bottom of the Studio tab.": "Se muestran al final de la pestaña Salón.",
  "Using the built-in four tips.": "Usando los cuatro consejos predeterminados.",
  "Customize the tips": "Personalizar los consejos",
  "+ Add a tip": "+ Agregar un consejo",
  "Back to the built-in tips": "Volver a los consejos predeterminados",
  "Tip": "Consejo",
  "Gift cards": "Tarjetas de regalo",
  "Show the gift card box": "Mostrar el recuadro de tarjetas de regalo",
  "Gift card amounts ($)": "Montos de tarjetas de regalo ($)",
  "Separate with commas.": "Sepáralos con comas.",
  "Default hair color": "Color de cabello predeterminado",
  "Service for this look": "Servicio para este look",
  "The “Book this look” button on the portfolio preselects this service.": "El botón “Reservar este look” del portafolio preselecciona este servicio.",
  "— none —": "— ninguno —",
  "Add sample items": "Agregar ejemplos",
  "Sample items added. Edit or delete them any time.": "Ejemplos agregados. Edítalos o bórralos cuando quieras.",
  "Shown on the homepage → Menu tab and in booking. Price is the “from” price; duration controls how much calendar time it takes.": "Aparece en el inicio → pestaña Menú y al reservar. El precio es el precio “desde”; la duración define cuánto tiempo ocupa en el calendario.",
  "Shown on the Menu tab and offered during booking. Optional extras clients can add to a service.": "Aparece en la pestaña Menú y se ofrece al reservar. Extras opcionales que los clientes pueden añadir a un servicio.",
  "Shown on the Portfolio page. Upload your best work (photos), and add a “before” photo to turn on the before/after slider.": "Aparece en la página Portafolio. Sube tu mejor trabajo (fotos) y agrega una foto de “antes” para activar el deslizador antes/después.",
  "Shown on the homepage → Stories tab. Only add real reviews you have permission to share.": "Aparece en el inicio → pestaña Reseñas. Agrega solo reseñas reales que tengas permiso de compartir.",
  "Shown on the homepage → Studio tab.": "Aparece en el inicio → pestaña Salón.",
  "Your employees, shown in “Meet the team” underneath your own profile on the homepage (photo, name, role, bio). Until you add someone, that section is hidden.": "Tus empleados, que aparecen en “Conoce al equipo” debajo de tu propio perfil en el inicio (foto, nombre, cargo, biografía). Hasta que agregues a alguien, esa sección se oculta.",

  // list editor
  "+ Add new": "+ Agregar",
  "Nothing here yet. Click “Add new”.": "Aún no hay nada. Haz clic en “Agregar”.",
  "Move up": "Subir",
  "Move down": "Bajar",
  "Untitled": "Sin título",
  "Hidden": "Oculto",
  "Edit": "Editar",
  "Close": "Cerrar",
  "Show on website": "Mostrar en el sitio web",
  "Save changes": "Guardar cambios",
  "Saving…": "Guardando…",
  "Delete": "Eliminar",
  "Saved. Your website is updated.": "Guardado. Tu sitio web ya está actualizado.",
  "Deleted.": "Eliminado.",
  "Delete “{name}”? This can't be undone.": "¿Eliminar “{name}”? No se puede deshacer.",
  "This section needs a one-time database update. Open Supabase → SQL Editor → New query, paste the SQL below, press Run, then reload this page.": "Esta sección necesita una actualización única de la base de datos. Abre Supabase → SQL Editor → New query, pega el SQL de abajo, presiona Run y recarga esta página.",
  "Spanish support needs a one-time database update. Open Supabase → SQL Editor → New query, paste the SQL below, press Run, then reload this page and save again.": "El soporte en español necesita una actualización única de la base de datos. Abre Supabase → SQL Editor → New query, pega el SQL de abajo, presiona Run, recarga esta página y guarda de nuevo.",

  // images
  "No photo": "Sin foto",
  "Replace": "Reemplazar",
  "Upload": "Subir",
  "Remove": "Quitar",
  "Uploading…": "Subiendo…",
  "Please choose an image file.": "Elige un archivo de imagen.",
  "Image is over 8 MB. Please choose a smaller one.": "La imagen supera 8 MB. Elige una más pequeña.",

  // bookings
  "Upcoming": "Próximas",
  "Pending": "Pendientes",
  "All": "Todas",
  "Cancelled": "Canceladas",
  "New requests arrive as “pending”. Confirm them, or cancel to free the time slot again.": "Las solicitudes nuevas llegan como “pendientes”. Confírmalas, o cancélalas para liberar el horario.",
  "Refresh": "Actualizar",
  "No bookings in this view.": "No hay reservas en esta vista.",
  "Client:": "Cliente:",
  "(first visit)": "(primera visita)",
  "Phone:": "Teléfono:",
  "Email:": "Correo:",
  "Ref:": "Ref.:",
  "Confirm": "Confirmar",
  "Mark completed": "Marcar como completada",
  "Cancel": "Cancelar",
  "Restore": "Restaurar",
  "pending": "pendiente",
  "confirmed": "confirmada",
  "completed": "completada",
  "cancelled": "cancelada",
  "est.": "est.",
  "deposit": "depósito",
  "Permanently delete {name}'s booking?": "¿Eliminar definitivamente la reserva de {name}?",

  // studio settings
  "Studio & website": "Salón y sitio web",
  "Your name, contact details, hours and the text on your site.": "Tu nombre, datos de contacto, horario y los textos de tu sitio.",
  "Salon": "Salón",
  "Salon name": "Nombre del salón",
  "Big wordmark in the header": "Nombre grande en el encabezado",
  "Subtitle": "Subtítulo",
  "Small text beside the name": "Texto pequeño junto al nombre",
  "Stylist name": "Nombre de la estilista",
  "City": "Ciudad",
  "Street address": "Dirección",
  "Phone": "Teléfono",
  "Directions note": "Nota de indicaciones",
  "e.g. Free parking out front": "p. ej. Estacionamiento gratis al frente",
  "Homepage & about": "Inicio y acerca de",
  "Hero paragraph": "Párrafo principal",
  "About headline": "Título de “Acerca de”",
  "About text": "Texto de “Acerca de”",
  "Portrait photo": "Foto de retrato",
  "Years of experience": "Años de experiencia",
  "Clients served": "Clientes atendidos",
  "shown as text, e.g. 4,200+": "se muestra como texto, p. ej. 4,200+",
  "Average rating": "Calificación promedio",
  "Look & feel": "Apariencia",
  "Default color shade": "Tono de color predeterminado",
  "Visitors can still change it themselves.": "Los visitantes pueden cambiarlo por su cuenta.",
  "Default mode": "Modo predeterminado",
  "Ivory (light)": "Marfil (claro)",
  "Black (dark)": "Negro (oscuro)",
  "Opening hours": "Horario de atención",
  "Clients can only book inside these hours.": "Los clientes solo pueden reservar dentro de este horario.",
  "Closed": "Cerrado",
  "to": "a",
  "Time between start times (minutes)": "Tiempo entre horas de inicio (minutos)",
  "Minimum notice (hours)": "Aviso mínimo (horas)",
  "Stops same-hour bookings": "Evita reservas de último momento",
  "opens": "abre",
  "closes": "cierra",
};
